head(iris,150)
xdata  <- iris$Sepal.Length
MinQ = quantile(xdata,0)
FQ = quantile(xdata,0.25)
SQ = quantile(xdata,0.5)
TQ = quantile(xdata,0.75)
MaxQ = quantile(xdata,1)
cat("Minimum = ",MinQ)
cat("First Quartile = ",FQ)
cat("Second Quartile = ",SQ)
cat("Third Quartile = ", TQ)
cat("Maximum = ",MaxQ)
AQ <- quantile(xdata,probs = c(0,0.25,0.50,0.75,1))
cat("All Quartiles",AQ)
summary(xdata)
boxplot(xdata,main = "InterQuartile Range For Sepal.Length",ylab = "xdata")
as.numeric(quantile(xdata,0.75) - quantile(xdata,0.25))
IQR(xdata)

