xdata <- c(5,10,12,17,20,25,27,30,35)
MinQ <- quantile(xdata,0)
FQ <- quantile(xdata,0.25)
SQ <- quantile(xdata,0.50)
TQ <- quantile(xdata,0.75)
MaxQ <- quantile(xdata,1)
cat("Minimum = ",MinQ)
cat("First Quartile = ",FQ)
cat("Second Quartile = ",SQ)
cat("Third Quartile = ",TQ)
cat("Maximum Quartile = ",MaxQ)
AQ <- quantile(xdata,probs = c(0,0.25,0.50,0.75,1))
cat("All  Quartiles = ",AQ)
summary(xdata)
boxplot(xdata,main = "InterQuartile Range(IQR)",ylab = "xdata")
as.numeric(quantile(xdata,0.75) - quantile(xdata,0.25))
IQR(xdata)
